name: Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install docfx
      run: choco install docfx -y
    - name: Build and Deploy packages
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: ./build.ps1 -t Deploy
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./dist
  docs:
    needs: deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        persist-credentials: false
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts
        path: ./dist
    - name: Deploy documents
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.PA_TOKEN }}
        branch: gh-pages
        folder: ./dist/docs/_site