name: Release

on:
  release:
    types: [published]

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install docfx
      run: choco install docfx -y
    - name: Build and Deploy packages
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: ./build.ps1 -t Deploy
    - name: Deploy documents
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        token: ${{ secrets.PA_TOKEN }}
        branch: gh-pages
        folder: ./dist/docs/_site